# Generated by Django 4.1.13 on 2024-04-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='summry',
        ),
        migrations.AddField(
            model_name='post',
            name='event_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='event_time',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
