# Generated by Django 4.1.13 on 2024-04-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_delete_test_rename_title_post_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
