# Generated by Django 4.1.13 on 2024-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0004_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='event_date',
            new_name='eventDate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='event_name',
            new_name='eventName',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='summry',
            new_name='eventSummary',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='event_time',
            new_name='eventTime',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='eventPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
