# Generated by Django 4.1.13 on 2024-04-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0005_rename_event_date_post_eventdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='eventPhoto',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
    ]
